  GNU nano 6.2                                                                                  docker-compose.yml
version: "3.5"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
#   image: ghcr.io/linuxserver/jellyfin:arm64v8-10.8.12
    container_name: jellyfin
    network_mode: "bridge"
    volumes:
      - /home/traver/docker/jellyfin/config:/config
      - /home/traver/docker/jellyfin/cache:/cache
      - /media/nasmedia:/media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://docker2
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    #group_add:
    #  - "109"  # Change this to match your "render" host group id and remove this comment
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128