services:
  ripper:
    container_name: Ripper
    image: rix1337/docker-ripper:manual-latest
    privileged: true
    ports:
      - "port:9090"  # Replace 'port' with your actual port (e.g., "8080:9090")
    volumes:
      - /path/to/config/:/config:rw
      - /path/to/rips/:/out:rw
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg0:/dev/sg0
    environment:
      - OPTIONAL_WEB_UI_PATH_PREFIX=/ripper-ui
      - OPTIONAL_WEB_UI_USERNAME=username
      - OPTIONAL_WEB_UI_PASSWORD=securepassword
      - DEBUGTOWEB=true
    restart: unless-stopped